/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import AccesoADatos.CelebracionAD;
import Entidades.Celebracion;
import Utils.AlgoritmosDeOrdenamiento;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ocerv
 */
public class OrdenarCelebraciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrdenarCelebraciones.class.getName());
    private DefaultTableModel modeloTabla;
    private final ArrayList<Celebracion> listaDeCelebraciones = CelebracionAD.consultarCelebraciones();
    

    /**
     * Creates new form OrdenarCelebraciones
     */
    public OrdenarCelebraciones() {
        initComponents();
        setLocationRelativeTo(null); // PAra que la ventana aparezca en el centro de la pantalla, y no en un punto específico
        configurarTabla();
    }
    
    private void configurarTabla(){
        String[] nombresColumnas = {"ID", "Fecha", "Descripción", "País"};
        modeloTabla = new DefaultTableModel(nombresColumnas, 0) {
            //Convierte las celdas de la tabla en No Editables
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        // Asigna el modelo recién creado a la tabla que va a mostar los datos
        tblCelebracionesOrdenadas.setModel(modeloTabla);
    }
    
    private void cargarDatosEnTabla(ArrayList<Celebracion> pListaDeCelebraciones){
        modeloTabla.setRowCount(0);
        Iterator<Celebracion> iterador = pListaDeCelebraciones.iterator();

        while(iterador.hasNext()){
            Celebracion celebracion = iterador.next();
            Object[] fila = new Object[4];
            fila[0] = celebracion.getIdDeLaCelebracion();
            fila[1] = celebracion.getFecha();
            fila[2] = celebracion.getDescripcion();
            fila[3] = celebracion.getPais();
            
            modeloTabla.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnOrdenOriginal = new javax.swing.JButton();
        btnMergeSort = new javax.swing.JButton();
        btnInsertionSort = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCelebracionesOrdenadas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ordenar Celebraciones");
        jLabel1.setToolTipText("");

        btnOrdenOriginal.setText("Orden Original");
        btnOrdenOriginal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrdenOriginalMouseClicked(evt);
            }
        });

        btnMergeSort.setText("Merge Sort");
        btnMergeSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMergeSortMouseClicked(evt);
            }
        });

        btnInsertionSort.setText("Insertion Sort");
        btnInsertionSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertionSortMouseClicked(evt);
            }
        });

        btnVolver.setText("VOLVER");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        tblCelebracionesOrdenadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCelebracionesOrdenadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOrdenOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInsertionSort, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMergeSort, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnVolver)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenOriginal)
                    .addComponent(btnInsertionSort)
                    .addComponent(btnMergeSort))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        OrdenarCelebraciones.this.dispose();
        VentanaPrincipal ventana = new VentanaPrincipal();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnOrdenOriginalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenOriginalMouseClicked
        // TODO add your handling code here:
        ArrayList<Celebracion> copiaCelebraciones = new ArrayList(listaDeCelebraciones);
        cargarDatosEnTabla(copiaCelebraciones);
    }//GEN-LAST:event_btnOrdenOriginalMouseClicked

    private void btnInsertionSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertionSortMouseClicked
        // TODO add your handling code here:
        ArrayList<Celebracion> copiaCelebraciones = new ArrayList(listaDeCelebraciones);
        AlgoritmosDeOrdenamiento.ordenamientoPorInsercion(copiaCelebraciones);
        cargarDatosEnTabla(copiaCelebraciones);
    }//GEN-LAST:event_btnInsertionSortMouseClicked

    private void btnMergeSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMergeSortMouseClicked
        // TODO add your handling code here:
        ArrayList<Celebracion> copiaCelebraciones = new ArrayList(listaDeCelebraciones);
        AlgoritmosDeOrdenamiento.ordenamientoMergeSort(copiaCelebraciones);
        cargarDatosEnTabla(copiaCelebraciones);
    }//GEN-LAST:event_btnMergeSortMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OrdenarCelebraciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertionSort;
    private javax.swing.JButton btnMergeSort;
    private javax.swing.JButton btnOrdenOriginal;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCelebracionesOrdenadas;
    // End of variables declaration//GEN-END:variables
}
