/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author ocerv
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null); // PAra que la ventana aparezca en el centro de la pantalla, y no en un punto específico
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnConsultarCelebraciones = new javax.swing.JButton();
        btnEditarCelebraciones = new javax.swing.JButton();
        btnInvertirNombrePais = new javax.swing.JButton();
        btnOrdenarCelebraciones = new javax.swing.JButton();
        btnRegistrarCelebraciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jButton2.setText("Registrar Celebraciones");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Celebraciones - Inicio");
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(400, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(jLabel1);
        jLabel1.setText("Listado de Celebraciones");
        jLabel1.setToolTipText("");

        btnConsultarCelebraciones.setText("Consultar Celebraciones");
        btnConsultarCelebraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCelebracionesActionPerformed(evt);
            }
        });

        btnEditarCelebraciones.setText("Editar Celebraciones");
        btnEditarCelebraciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarCelebracionesMouseClicked(evt);
            }
        });

        btnInvertirNombrePais.setText("Invertir nombre de países");
        btnInvertirNombrePais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInvertirNombrePaisMouseClicked(evt);
            }
        });

        btnOrdenarCelebraciones.setText("Ordenar Celebraciones");

        btnRegistrarCelebraciones.setText("Registrar Celebraciones");
        btnRegistrarCelebraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCelebracionesActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.setToolTipText("");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarCelebraciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarCelebraciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInvertirNombrePais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrdenarCelebraciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarCelebraciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 158, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(0, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(btnRegistrarCelebraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarCelebraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarCelebraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvertirNombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrdenarCelebraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnRegistrarCelebracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCelebracionesActionPerformed
        // TODO add your handling code here:
        RegistrarCelebracion registrarCelebracion = new RegistrarCelebracion();
        registrarCelebracion.setVisible(true);
        VentanaPrincipal.this.dispose();
    }//GEN-LAST:event_btnRegistrarCelebracionesActionPerformed

    private void btnConsultarCelebracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCelebracionesActionPerformed
        // TODO add your handling code here:
        ConsultarCelebraciones consultarCelebraciones = new ConsultarCelebraciones();
        consultarCelebraciones.setVisible(true);
        VentanaPrincipal.this.dispose();
    }//GEN-LAST:event_btnConsultarCelebracionesActionPerformed

    private void btnEditarCelebracionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCelebracionesMouseClicked
        // TODO add your handling code here:
        EditarCelebracion editarCelebracion = new EditarCelebracion();
        editarCelebracion.setVisible(true);
        VentanaPrincipal.this.dispose();
    }//GEN-LAST:event_btnEditarCelebracionesMouseClicked

    private void btnInvertirNombrePaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvertirNombrePaisMouseClicked
        // TODO add your handling code here:
        InvertirPaises invertirPaises = new InvertirPaises();
        invertirPaises.setVisible(true);
        VentanaPrincipal.this.dispose();
    }//GEN-LAST:event_btnInvertirNombrePaisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCelebraciones;
    private javax.swing.JButton btnEditarCelebraciones;
    private javax.swing.JButton btnInvertirNombrePais;
    private javax.swing.JButton btnOrdenarCelebraciones;
    private javax.swing.JButton btnRegistrarCelebraciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
